version: '3.8'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - PEER1=localhost:3001
      - PEER2=localhost:3002

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - PEER1=localhost:3000
      - PEER2=localhost:3002

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - PEER1=localhost:3000
      - PEER2=localhost:3001
